/* Automatically generated by './build/bin/build-entry.js' */

import AdaptivePicture from './components/adaptivePicture/index.js';
import Alert from './components/alert/index.js';
import BackTop from './components/backTop/index.js';
import Badge from './components/badge/index.js';
import Blank from './components/blank/index.js';
import Breadcrumb from './components/breadcrumb/index.js';
import Button from './components/button/index.js';
import Checkbox from './components/checkbox/index.js';
import CheckboxGroup from './components/checkboxGroup/index.js';
import CircleProgress from './components/circleProgress/index.js';
import Collapse from './components/collapse/index.js';
import DatePicker from './components/datePicker/index.js';
import Drawer from './components/drawer/index.js';
import Dropdown from './components/dropdown/index.js';
import SectionTitle from './components/sectionTitle/index.js';
import Form from './components/form/index.js';
import Grid from './components/grid/index.js';
import InfoList from './components/infoList/index.js';
import DetailedList from './components/detailedList/index.js';
import Input from './components/input/index.js';
import InputNumber from './components/inputNumber/index.js';
import KeyValueLabel from './components/keyValueLabel/index.js';
import Spinner from './components/spinner/index.js';
import Loading from './components/loading/index.js';
import LoadingBar from './components/loadingBar/index.js';
import Menu from './components/menu/index.js';
import Message from './components/message/index.js';
import Modal from './components/modal/index.js';
import Notification from './components/notification/index.js';
import Thumbnail from './components/thumbnail/index.js';
import OnlineStatus from './components/onlineStatus/index.js';
import Overview from './components/overview/index.js';
import PageFooter from './components/pageFooter/index.js';
import PageHeader from './components/pageHeader/index.js';
import Pagination from './components/pagination/index.js';
import PictureBlank from './components/pictureBlank/index.js';
import Popover from './components/popover/index.js';
import Popup from './components/popup/index.js';
import Portlet from './components/portlet/index.js';
import Progress from './components/progress/index.js';
import Radio from './components/radio/index.js';
import RadioGroup from './components/radioGroup/index.js';
import RichEditor from './components/richEditor/index.js';
import Scrollbar from './components/scrollbar/index.js';
import Select from './components/select/index.js';
import Slider from './components/slider/index.js';
import Steps from './components/steps/index.js';
import Switch from './components/switch/index.js';
import Tabs from './components/tabs/index.js';
import Table from './components/table/index.js';
import Tag from './components/tag/index.js';
import Tooltip from './components/tooltip/index.js';
import Transfer from './components/transfer/index.js';
import Tree from './components/tree/index.js';
import Uploader from './components/uploader/index.js';
import Trend from './components/trend/index.js';
import Card from './components/card/index.js';
import Divider from './components/divider/index.js';
import Skeleton from './components/skeleton/index.js';
import Affix from './components/affix/index.js';
import Rate from './components/rate/index.js';
import Image from './components/image/index.js';
import MessageBox from './components/messageBox/index.js';
import InfiniteScroll from './components/infiniteScroll/index.js';
import PasswordLabel from './components/passwordLabel/index.js';
import Text from './components/text/index.js';
import BatteryCharge from './components/batteryCharge/index.js';
import CollapseTransition from './components/collapseTransition/index.js';
import TimeLine from './components/timeLine/index.js';
import RainbowText from './components/rainbowText/index.js';
import Drop from './components/drop/index.js';
import Link from './components/link/index.js';
import CascaderPanel from './components/cascaderPanel/index.js';
import Cascader from './components/cascader/index.js';
import Descriptions from './components/descriptions/index.js';
import LoadingIndicator from './components/loadingIndicator/index.js';
import Border from './components/border/index.js';
import Browser from './components/browser/index.js';
import Container from './components/container/index.js';
import NumericList from './components/numericList/index.js';
import Article from './components/article/index.js';
import LogList from './components/logList/index.js';
import Avatar from './components/avatar/index.js';
import ContainerCloseButton from './components/containerCloseButton/index.js';
import Statistic from './components/statistic/index.js';
import Space from './components/space/index.js';
import List from './components/list/index.js';
import Ribbon from './components/ribbon/index.js';
import ClearButton from './components/clearButton/index.js';
import CountDown from './components/countDown/index.js';
import CountTo from './components/countTo/index.js';
import Empty from './components/empty/index.js';
import Autocomplete from './components/autocomplete/index.js';
import ColorPicker from './components/colorPicker/index.js';
import TimeSelect from './components/timeSelect/index.js';
import PopConfirm from './components/popConfirm/index.js';
import Calendar from './components/calendar/index.js';
import StatisticCard from './components/statisticCard/index.js';
import StatisticBar from './components/statisticBar/index.js';
import Status from './components/status/index.js';

export default {
  AdaptivePicture,
  Alert,
  BackTop,
  Badge,
  Blank,
  Breadcrumb,
  Button,
  Checkbox,
  CheckboxGroup,
  CircleProgress,
  Collapse,
  DatePicker,
  Drawer,
  Dropdown,
  SectionTitle,
  Form,
  Grid,
  InfoList,
  DetailedList,
  Input,
  InputNumber,
  KeyValueLabel,
  Spinner,
  Loading,
  LoadingBar,
  Menu,
  Message,
  Modal,
  Notification,
  Thumbnail,
  OnlineStatus,
  Overview,
  PageFooter,
  PageHeader,
  Pagination,
  PictureBlank,
  Popover,
  Popup,
  Portlet,
  Progress,
  Radio,
  RadioGroup,
  RichEditor,
  Scrollbar,
  Select,
  Slider,
  Steps,
  Switch,
  Tabs,
  Table,
  Tag,
  Tooltip,
  Transfer,
  Tree,
  Uploader,
  Trend,
  Card,
  Divider,
  Skeleton,
  Affix,
  Rate,
  Image,
  MessageBox,
  InfiniteScroll,
  PasswordLabel,
  Text,
  BatteryCharge,
  CollapseTransition,
  TimeLine,
  RainbowText,
  Drop,
  Link,
  CascaderPanel,
  Cascader,
  Descriptions,
  LoadingIndicator,
  Border,
  Browser,
  Container,
  NumericList,
  Article,
  LogList,
  Avatar,
  ContainerCloseButton,
  Statistic,
  Space,
  List,
  Ribbon,
  ClearButton,
  CountDown,
  CountTo,
  Empty,
  Autocomplete,
  ColorPicker,
  TimeSelect,
  PopConfirm,
  Calendar,
  StatisticCard,
  StatisticBar,
  Status
};
